name: Docker-CI-CD

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Lint 
        run: npm run lint
      
      - name: Test Run
        run: npm test
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t calculatrice:${{ github.ref_name  }} .
      
      - name: Tag Docker image with latest
        run: |
          docker tag calculatrice:${{ github.ref_name  }} ${{ secrets.DOCKERHUB_USERNAME }}/calculatrice:latest

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/calculatrice:${{ github.ref_name  }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/calculatrice:latest

      - name: Generate GitHub Release Notes
        uses: softprops/action-gh-release@v1
        with:
          files: ''
          body: 'Release ${{ github.ref_name  }}'
          token: ${{ secrets.GITHUB_TOKEN }}
